---
name: App-ZofCMS-Plugin-FormToDatabase
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: simple insertion of query into database
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0105
  DBI: 1.602
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::FormToDatabase:
    file: lib/App/ZofCMS/Plugin/FormToDatabase.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
